### ISSUE TITLE
Reordering through different manipulations

### ISSUE THREAD

**Issue by bobmulder** [spatie/menu#103]
Hi neighbours (I'm dutch hehe :)),

I wonder if this library supports ordering items after they have been added.

My usecase: through different ServiceProviders I'd like to add links after another specific link.

I couldn't manage this one yet, hopefuly there is a possibility to make this work!

Regards, Bob

**Comment by freekmurze** [comment]
This currently isn't supported. If you can make this work with a simple change, feel free to PR it (along with tests and an updated readme)

**Comment by rumeau** [comment]
I've submitted a PR #113 in order to allow ordering of items. Is this still required or is there any interest on it?

@freekmurze would yo mind taking a look on it?

Greetings

**Comment by bobmulder** [comment]
That's looking promising, @rumeau! Unfortunately I totally forgot about this feature, but I'd love to use it with this lib!
