### ISSUE TITLE
addClass methods for View::Create()

### ISSUE THREAD

**Issue by NoxxieNl** [spatie/menu#104]
I am currently trying to get a complex menu work with this package. Package works create but for my personal menu I grab to the `raw` method to often so I tried to refactor it and use the default functions included.

However as soon as I am using the `View::create()` method I cannot style the `<li>` surrounding that view creation. When I do:

````php
      $this->menu->add(
            View::create('partials.menu.link', [
                'name' => $name,
                'icon' => $icon,
                'url' => $url
            ])
            ->addClass('kt-menu__item')
            ->setAttribute('aria-haspopup', 'true')
        )
````

I get the error `addClass` and `setAttribute` does not exist.
When I had those methods one level up (after the `add` method) they are appended to the parent `ul`. How can give styling to the `li` where a view created the content of that `li`?

Am I missing something here?

**Comment by NoxxieNl** [comment]
Nevermind,
Still learning the package...

and `addParentClass()` and `setParentAttribute()` does exactly what I want in styling the `<li>`...

**Comment by sebastiandedeyne** [comment]
Yep :) `addClass` adds a class to the `a` tag when adding plain links. This doesn't make sense with `raw` content, which is why they don't exist.
