### ISSUE TITLE
add breadcrumbs option

### ISSUE THREAD

**Issue by Grummfy** [spatie/menu#111]
Hello,
I think a nice feature, could be a possibility to generate a breadcrumbs, something similar to
https://gist.github.com/Grummfy/740a36752d03bbd6a8e9ac8e058e6276

Imagine we have a menu like this
```
root
  |_ A
    |_ A.1
    |_ A.2
      |_ A.2.1
  |_ C
    |_ C.1
  |_ D
```

if we are in A.2.1, the breadcrumbs will be something similar to
```
root / A / A.2 / A.2.1
```

**Comment by freekmurze** [comment]
Right now, we don't have a need for this ourselves.

If the code to achieve this is simple, we'd accept a PR with tests and an updated readme that adds this to the package.
