### ISSUE TITLE
Exception when prepend is instance of Item

### ISSUE THREAD

**Issue by ppx17** [spatie/menu#127]
I'm experiencing an issue with the following four lines.

https://github.com/spatie/menu/blob/926c8f24f4e84a5bdc79af283a33b7db03684547/src/Menu.php#L720-L724

The issue occurs when $this->prepend contains a Spatie\Menu\Html instance. This object implements the Item interface, and L720 makes me believe this should be valid. However, the render method concats the item into a string, triggering the `__toString()` method, which does not exist on the Item interface.

Hence I end up with the following exception:

`Object of class Spatie\Menu\Html could not be converted to string`

I think the easiest solution would be to check if $this->prepend is an item, and then call ~~`->toHtml()`~~`->render()` on it. Should I open a PR for this, or am I missing something else?

**Comment by sebastiandedeyne** [comment]
Tagged a fix in `2.10.3`!
