### ISSUE TITLE
Link Target

### ISSUE THREAD

**Issue by OppPMatos** [spatie/menu#129]
Hello.
I can't seem to find on the documentation how to set a link's target.
Is it possible?

**Comment by allenjd3** [comment]
Should be able to use 
```php
setAttribute("target", "_top")
```
Similarly to addClass

**Comment by OppPMatos** [comment]
> Should be able to use
> 
> ```
> setAttribute("target", "_top")
> ```
> 
> Similarly to addClass

Thank you.
