### ISSUE TITLE
Add class to <li> with submenu

### ISSUE THREAD

**Issue by weijinnx** [spatie/menu#38]
When I using submenu() function to create submenu, I need to add class to **li** like:
```html
<ul>
  <li><a href="#">Home</a></li>
  <li class="submenu">
    <a href="#">Submenu</a>
    <ul>...</ul>
  </li>
</ul>
```

**Comment by sebastiandedeyne** [comment]
Adding classes to specific parents (`li`'s) isn't supported yet. I'll try to add this in the near future.

**Comment by mikerockett** [comment]
Just bumped into the need for this as well. Could it not be done with a simple signature like this?

```
submenu(attrs, header, menu | attrs, menu)
```

**Comment by yuriimuratov** [comment]
@weijinnx @mikerockett 
I think you can do it with parent-attributes methods like Menu::addParentClass()

https://docs.spatie.be/menu/v2/controlling-the-html-output/parent-attributes

**Comment by sebastiandedeyne** [comment]
If anyone's up for looking into this, feel free to send a (tested) PR!

**Comment by hulkur** [comment]
This can be closed as Menu has `addParentClass()` and it adds class to parent `li`

Tested with example from readme https://github.com/spatie/menu#not-afraid-of-depths
