### ISSUE TITLE
[Question] Bootstrap 4 style

### ISSUE THREAD

**Issue by Xety** [spatie/menu#39]
Hello,
I was wondering how can i set a `nav` element instead of the `ul` and also usa an `a` element instead of a `li`. The menu that i want look like that :
```html
<nav class="nav nav-menu flex-column">
    <a class="nav-link active" href="#">
        <i class="fa fa-user"></i> Account
    </a>
    <a class="nav-link" href="#">
        <i class="fa fa-bell-o"></i> Notifications
    </a>
</nav>
```
I saw nothing about that in the doc.

**Comment by sebastiandedeyne** [comment]
Currently only list elements are supported. Doesn't bootstrap only depend on the class names, allowing you to use it as is?

**Comment by Kristories** [comment]
@sebastiandedeyne B4 use `a` tag (not `li`) to determine whether an item is active or not.
