### ISSUE TITLE
PHP 5.6 support

### ISSUE THREAD

**Issue by luwes** [spatie/menu#4]
Hi fellow Antwerpenaar,

Thanks for this great package!
I was wondering if it would be difficult to make this library work in PHP 5.6?

**Comment by freekmurze** [comment]
Ha ene van 't stad! :-)

I think adding PHP 5.6 would not be that hard. Because we don't do PHP 5 ourselves anymore we don't want to create (or maintain) PHP 5 packages anymore.

So if you want this, fork our code and maintain your own version.
