### ISSUE TITLE
Make the Menu class serializable

### ISSUE THREAD

**Issue by m1guelpf** [spatie/menu#52]
## Use Case:
I am trying to make my application faster, and generating the menu every time seems like a waste of time, so I would like to cache it.

## Problem:
The Menu class isn't serializable so it can't be cached.

## Solution:
Make the Menu class and its subclasses serializable.

**Comment by sebastiandedeyne** [comment]
If you want to cache the menu, I'd recommend caching the rendered html instead.

On the other hand, if this is a minor change, I'd accept a non-breaking PR with a test.
