### ISSUE TITLE
Renderer class - decoupled from Menu

### ISSUE THREAD

**Issue by Gummibeer** [spatie/menu#62]
Menus are something very special, like nearly all frontend/display things.
There are some common structures that cover ~90% but in all other cases I have to override the Menu and can Just have one render style.

If I think about dashboards you have one sidebar menu, one in the top navbar and one in the footer.

With a dedicated render class that would be a lot easier.

```php
$menu = new Menu(); // create the menu with items
$menu->render(); // default one
$menu->render('bootstrap-3'); // bootstrap3 renderer
$menu->render('dropdown'); // dropdown renderer
```

This would be easy achievable by an Interface for renderers and the manager-driver approach that's massively used in laravel. By this it would be possible to create ready to use renderers in foreign packages and just register them.

It will also help to remove `addClass` for all items if all need `.item`. And enable icons in the menu and to add bootstrap `.caret` and all the other stuffs.

I would be fine to create a PR for this, just want to know if it is wanted and the way to solve the Problem ist ok!?

**Related to:**
* #28
* #39

**Comment by Gummibeer** [comment]
A quick'n'dirty example of what I mean/want - no final code, without checks and all this stuff, but the idea should be clear.

**Menu**
```php
<?php
namespace Spatie\Menu;

use Spatie\Menu\Renderer\DefaultRenderer;

class Menu implements Item, Countable, HasHtmlAttributes, HasParentAttributes
{
    protected $renderer = [
        'default' => DefaultRenderer::class,
    ];

    public function addRenderer($key, $renderer) {
        $this->renderer[$key] = $renderer;
    }

    public function render($key = 'default') {
        return (new $this->renderer[$key])->render($this);
    }
}
```

**RendererInterface**
```php
<?php
namespace Spatie\Menu;

interface RendererInterface
{
    public function render(Menu $menu);
}
```

**DefaultRenderer**
```php
<?php
namespace Spatie\Menu\Renderer;

use Spatie\Menu\RendererInterface;

interface DefaultRenderer implement RendererInterface
{
    public function render(Menu $menu): string
    {
        $tag = new Tag('ul', $menu->htmlAttributes);
        $contents = array_map([$this, 'renderItem'], $menu->items);
        $output = $menu->prepend.$tag->withContents($contents).$menu->append;
        if (! empty($menu->wrap)) {
            return Tag::make($menu->wrap[0], new Attributes($menu->wrap[1]))->withContents($output);
        }

        return $output;
    }

    protected function renderItem(Item $item, Menu $menu): string
    {
        $attributes = new Attributes();
        if ($item->isActive()) {
            $attributes->addClass($menu->activeClass);
        }
        if ($item instanceof HasParentAttributes) {
            $attributes->setAttributes($item->parentAttributes());
        }

        return Tag::make('li', $attributes)->withContents($item->render());
    }
}
```

**Comment by sebastiandedeyne** [comment]
Hi @Gummibeer 

I'd love to see this in the package some day, it's actually already on the roadmap for the next major version. It could be a while until I get to it though, since other projects are more prioritised at the moment.

Thanks for your thoughts, I'll definitely keep them in mind when building this!

**Comment by Gummibeer** [comment]
Will you accept a PR that adds this Feature? I can't promise but if you will I could try to find some time.

**Comment by sebastiandedeyne** [comment]
I don't think I want to maintain the complexity at the moment, since I don't know what the next major version is going to look like. This library already has a lot of feature requests that I'd like to take in account, so I'd rather keep things kinda simple now so I don't need to remove anything in the next version if I change my mind about the architecture.

I hope that kinda makes sense 😅
