### ISSUE TITLE
Update for Bootstrap 4

### ISSUE THREAD

**Issue by mrk-j** [spatie/menu#63]
Hi there,

We are using `spatie/laravel-menu` and therefore `spatie/menu` in a project that is using Bootstrap 4. In Bootstrap 4 the markup for dropdowns changed, they are not using an `<ul>` for dropdowns anymore. We made [quick fix](https://github.com/digifactory/menu/commit/c6fabde4c1d5d52076635d33504798946d0bc03a) to enable us to use a `<div>` instead of an `<ul>` and not wrap the links in an `<li>`.

If we create some tests and update the documentation accordingly, are you willing to merge this?

Thanks in advance 👍

**Comment by sebastiandedeyne** [comment]
I'd like to add custom renderers in the future (see #62) but that's probably gonna take a while. In the mean time I'd accept PR that add's this, so I say go for it :)

**Comment by m-bosch** [comment]
Thnx @sebastiandedeyne, 

We are experiencing some issues with the 'active'-state as well now we have changed it for the dropdown items so we will investigate this as well.

**Comment by mrk-j** [comment]
Please see #64.
