### ISSUE TITLE
Option to set active class to link element

### ISSUE THREAD

**Issue by mallardduck** [spatie/menu#66]
I believe that the ability to set the active class on the link element itself should be added. If it's already possible and I just overlooked the functionality I apologize, but I haven't seen an obvious way how to do it yet.

This would be useful whether it's implemented as an explicit feature or an implicit feature of using the `withoutParentTag` method. After spending some time debugging why my menu's active links weren't set I think I chased it down to using that method.

I am using Bulma.css, so the navbar menus are just plain anchor tags meaning I use `withoutParentTag`. So the issue I'm having is that the active class setting feature becomes useless since it applies to the parents by default.

Current Output:
Route: /blog
```
<div class="navbar-end">
<a href="/" class="navbar-item">Home</a>
<a href="/blog" class="navbar-item">Blog</a>
<a href="/about" class="navbar-item">About</a>
</div>
```

Expected Output:
Route: /blog
```
<div class="navbar-end">
<a href="/" class="navbar-item">Home</a>
<a href="/blog" class="navbar-item is-active">Blog</a>
<a href="/about" class="navbar-item">About</a>
</div>
```

Current Output w/ Parents:
Route: /blog
```
<div class="navbar-end">
<li><a href="/" class="navbar-item">Home</a></li>
<li class="is-active"><a href="/blog" class="navbar-item">Blog</a></li>
<li><a href="/about" class="navbar-item">About</a></li>
</div>
```

**Comment by sebastiandedeyne** [comment]
This was added in the latest version of the package, 2.5.0 :)

The method is `setActiveClassOnLink`. Think it's missing from the docs though, I'll try to get to that soon!
