### ISSUE TITLE
Adding active class on wrapper element

### ISSUE THREAD

**Issue by strainovic** [spatie/menu#67]
I have a situation with submenu where I need to add custom active class on wrapper element (default element is 'ul') to show submenu items on page when one of submenu items is clicked.

Currently, this package add active class on parent 'li' element but not on 'ul'.

How would you handle it?

I have this:

```
<ul class='menu'>
  <li class='active'>
    <a href='#'>Dropdown</a>
    <ul>
      <li class='active'>Submenu item 1</li>
      <li>Submenu item 2</li>
    </ul>
  </li>
</ul>
```

But I need this:

```
<ul class='menu'>
  <li class='active'>
    <a href='#'>Dropdown</a>
    <ul class='show'>
      <li class='active'>Submenu item 1</li>
      <li>Submenu item 2</li>
    </ul>
  </li>
</ul>
```

'show' class on submenu wrapper 'ul' element.

Thanks!

**Comment by sargilla** [comment]
I need this, add show class to ul element of active tree.

**Comment by ju5t** [comment]
For anyone looking for an answer.

You could use something along the lines of the below on the `Menu` within your `submenu`.

```php
->each(function (Link $link) {
    if ($link->isActive()) {
        $link->addParentClass('active');
    }
})
```
