### ISSUE TITLE
Add exact-active class to elements that have the exact url

### ISSUE THREAD

**Issue by sebastiandedeyne** [spatie/menu#68]
Consider the route `/people/sebastian`. In this case, a menu item that links to `/people` and a menu item that links to `/people/sebastian` will have an `active` class.

We want to be able to add a second `exact-active` class when the page is an _exact_ match. So `/people` will _not_ have an `exact-active` class, `/people/sebastian` will.

Vue-router also has a similar feature: https://router.vuejs.org/api/#exact

**Comment by Joucke** [comment]
Submitted PR #74 to implement this. Something went wrong with typing the title, I'm hoping this will link the issue to the PR :)
