### ISSUE TITLE
Menu::wrap wraps menu and link element in Menu::submenu

### ISSUE THREAD

**Issue by crazytinkas** [spatie/menu#91]
$menu_a = Menu::new()
  ->link( '#', 'SubMenu Item 1' )
  ->link( '#', 'SubMenu Item 2' )
  ->link( '#', 'SubMenu Item 3' )
  ->wrap( 'div', ['class' => 'someclass'] );

$menu = Menu::new()
  ->link( '#', 'Menu Item 1' )
  ->link( '#', 'Menu Item 2' )
  ->submenu( Link::to( '#', 'Menu Item 3' ), $menu_a );

echo $menu->render();

Outputs

```
<ul>
    <li><a href="#">Menu Item 1</a></li>
    <li><a href="#">Menu Item 2</a></li>
    <li>
        <div class="someclass"><a href="#">Menu Item 3</a>
            <ul>
                <li><a href="#">SubMenu Item 1</a></li>
                <li><a href="#">SubMenu Item 2</a></li>
                <li><a href="#">SubMenu Item 3</a></li>
            </ul>
        </div>
    </li>
</ul>
```

Should Output

```
<ul>
    <li><a href="#">Menu Item 1</a></li>
    <li><a href="#">Menu Item 2</a></li>
    <li>
        <a href="#">Menu Item 3</a>
        <div class="someclass">
            <ul>
                <li><a href="#">SubMenu Item 1</a></li>
                <li><a href="#">SubMenu Item 2</a></li>
                <li><a href="#">SubMenu Item 3</a></li>
            </ul>
        </div>
    </li>
</ul>

```

**Comment by makroxyz** [comment]
Any suggestions on this? Is there any workaround?
Thanks in advance

**Comment by crazytinkas** [comment]
I'm just outputting the menu unwrapped, then using jquery/js to wrap the submenu once rendered. Not ideal, but it works.
Add an arbitrary junk class to your submenu( ->addClass('whatever')), then use jQuery.wrap on that class to wrap it in the required div.
